version: '3.7'
services:
    composer:
        container_name: composer-app
        image: composer
        command: update
        volumes:
           - ./app:/app
    php:
        container_name: php-fpm
        build: ./php
        ports:
            - "9000:9000"
        volumes:
            - ./app:/app           
        env_file:
            - .env       
        depends_on: 
            - composer
        networks:
            - php
    nginx:
        container_name: nginx
        build: ./nginx
        restart: on-failure
        ports:
            - "8080:80"
        depends_on: 
            - php
        networks:
            - php
        volumes:
            - ./nginx/logs:/var/log/nginx:cached
            - ./app:/app

networks:
    php:
